repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.0
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
        args: [ --check ]

# TODO: consider adding pre-commit hooks for uv, along the lines of pip-tools:
# https://pypi.org/project/pip-tools/
